exports.userSeed = [
  {
    fullName: "Carmine Amaya",
    userName: "camaya0",
    email: "camaya0@cpanel.net",
    password: "dN9@+~?/oa4w",
    active: true,
  },
  {
    fullName: "Kary Henden",
    userName: "khenden1",
    email: "khenden1@trellian.com",
    password: "wP0*rG{r\\J%PZ*cH",
    active: false,
  },
  {
    fullName: "Catlee Cantillion",
    userName: "ccantillion2",
    email: "ccantillion2@elegantthemes.com",
    password: "bM7{15s6EJweKG*8",
    active: true,
  },
  {
    fullName: "Bentlee Ledwidge",
    userName: "bledwidge3",
    email: "bledwidge3@blog.com",
    password: "oZ5#!\\hSqm9",
    active: false,
  },
  {
    fullName: "Timoteo Naseby",
    userName: "tnaseby4",
    email: "tnaseby4@ed.gov",
    password: "yP9&T@,xi_ZkCP8W",
    active: false,
  },
  {
    fullName: "Binnie Newlin",
    userName: "bnewlin5",
    email: "bnewlin5@furl.net",
    password: "rL2*8<hr",
    active: true,
  },
  {
    fullName: "Falito Jeckell",
    userName: "fjeckell6",
    email: "fjeckell6@nationalgeographic.com",
    password: "lW4_#=4EI",
    active: true,
  },
  {
    fullName: "Humbert Conen",
    userName: "hconen7",
    email: "hconen7@kickstarter.com",
    password: "yH2!)g)go#{sn",
    active: true,
  },
  {
    fullName: "Etti Rowesby",
    userName: "erowesby8",
    email: "erowesby8@themeforest.net",
    password: 'yY0.aipj#>"7(>ag',
    active: false,
  },
  {
    fullName: "Claudetta Silley",
    userName: "csilley9",
    email: "csilley9@list-manage.com",
    password: "jK7'o<btnVa",
    active: false,
  },
  {
    fullName: "Kalvin Antoszczyk",
    userName: "kantoszczyka",
    email: "kantoszczyka@samsung.com",
    password: 'lF3"3`fw',
    active: true,
  },
  {
    fullName: "Kimberlyn Panks",
    userName: "kpanksb",
    email: "kpanksb@ameblo.jp",
    password: "yA6&*pSoUiUb2mq",
    active: false,
  },
  {
    fullName: "Dorothee Prangnell",
    userName: "dprangnellc",
    email: "dprangnellc@dailymotion.com",
    password: "xH4)svgK.",
    active: false,
  },
  {
    fullName: "Aldin Speake",
    userName: "aspeaked",
    email: "aspeaked@nyu.edu",
    password: "cE3?Yh,'",
    active: false,
  },
  {
    fullName: "Tore Scothern",
    userName: "tscotherne",
    email: "tscotherne@xrea.com",
    password: 'vU4"ozrC\\dVy9_40',
    active: true,
  },
  {
    fullName: "Vladamir Undy",
    userName: "vundyf",
    email: "vundyf@networksolutions.com",
    password: "iT0*vbYoHpj",
    active: false,
  },
  {
    fullName: "Darb Fullerton",
    userName: "dfullertong",
    email: "dfullertong@nymag.com",
    password: "nO4{j/wY)u",
    active: false,
  },
  {
    fullName: "Gianina Clendinning",
    userName: "gclendinningh",
    email: "gclendinningh@delicious.com",
    password: "hN3@uOHCy",
    active: true,
  },
  {
    fullName: "Gasparo Moult",
    userName: "gmoulti",
    email: "gmoulti@list-manage.com",
    password: "sO4/ud(+GwuJ@",
    active: false,
  },
  {
    fullName: "Latia Severy",
    userName: "lseveryj",
    email: "lseveryj@paginegialle.it",
    password: "bR5'52zR$|vP6.sg",
    active: false,
  },
  {
    fullName: "Agnes Kiff",
    userName: "akiffk",
    email: "akiffk@usgs.gov",
    password: "wY5+{5VrX/X",
    active: false,
  },
  {
    fullName: "Aurthur Di Pietro",
    userName: "adil",
    email: "adil@wikia.com",
    password: "iR4>>M&>",
    active: true,
  },
  {
    fullName: "Cinderella Loudon",
    userName: "cloudonm",
    email: "cloudonm@indiatimes.com",
    password: "xN4\\#g1s{",
    active: false,
  },
  {
    fullName: "Jen Jekyll",
    userName: "jjekylln",
    email: "jjekylln@reddit.com",
    password: "wL4\\j>}cj_cHF(r",
    active: true,
  },
  {
    fullName: "Allistir Gyorgy",
    userName: "agyorgyo",
    email: "agyorgyo@mail.ru",
    password: "sP1,Jip8qtwUo",
    active: true,
  },
  {
    fullName: "Cornelia Balham",
    userName: "cbalhamp",
    email: "cbalhamp@flavors.me",
    password: "bL0#lDs{oG!b",
    active: false,
  },
  {
    fullName: "Tristam Hallsworth",
    userName: "thallsworthq",
    email: "thallsworthq@cpanel.net",
    password: "fC0{4%~,",
    active: false,
  },
  {
    fullName: "Dacia Probart",
    userName: "dprobartr",
    email: "dprobartr@comsenz.com",
    password: "kZ0(z>oS$mks~&kk",
    active: true,
  },
  {
    fullName: "Uriel Taft",
    userName: "utafts",
    email: "utafts@dailymail.co.uk",
    password: "bQ8>?UX5kk`K",
    active: true,
  },
  {
    fullName: "Hulda Medlar",
    userName: "hmedlart",
    email: "hmedlart@cbslocal.com",
    password: "xN1/@}>g%G.iE",
    active: true,
  },
  {
    fullName: "Gianina Jiroutek",
    userName: "gjirouteku",
    email: "gjirouteku@seesaa.net",
    password: 'cG0"%>Sm',
    active: false,
  },
  {
    fullName: "Junina Alger",
    userName: "jalgerv",
    email: "jalgerv@go.com",
    password: "kY1|>|fHH",
    active: true,
  },
  {
    fullName: "Grete Durbann",
    userName: "gdurbannw",
    email: "gdurbannw@archive.org",
    password: "qP1.M7D7?'wyFxM",
    active: false,
  },
  {
    fullName: "Farrand Mantione",
    userName: "fmantionex",
    email: "fmantionex@ftc.gov",
    password: 'uY6#csA_rGVIs"Cp',
    active: false,
  },
  {
    fullName: "Bev Tomaszewski",
    userName: "btomaszewskiy",
    email: "btomaszewskiy@imdb.com",
    password: "uZ7(#XcKBACy",
    active: true,
  },
  {
    fullName: "Sharia Prantoni",
    userName: "sprantoniz",
    email: "sprantoniz@chicagotribune.com",
    password: "pZ8!E`Cca",
    active: true,
  },
  {
    fullName: "Danyelle Purves",
    userName: "dpurves10",
    email: "dpurves10@wufoo.com",
    password: "zH7|lI=Mw",
    active: true,
  },
  {
    fullName: "Cesya McCrow",
    userName: "cmccrow11",
    email: "cmccrow11@columbia.edu",
    password: "zG7,y>Q|!$nN..C",
    active: false,
  },
  {
    fullName: "Rafael Hawler",
    userName: "rhawler12",
    email: "rhawler12@alibaba.com",
    password: "vR9{sE0%(XCmH",
    active: true,
  },
  {
    fullName: "Lucais Joberne",
    userName: "ljoberne13",
    email: "ljoberne13@addthis.com",
    password: "zK9`O<jN",
    active: false,
  },
  {
    fullName: "Ingaborg Powlett",
    userName: "ipowlett14",
    email: "ipowlett14@elegantthemes.com",
    password: "wF7%jf7{DXI92T",
    active: true,
  },
  {
    fullName: "Doe Callaway",
    userName: "dcallaway15",
    email: "dcallaway15@acquirethisname.com",
    password: "lD6`rPHLJ'THxz",
    active: true,
  },
  {
    fullName: "Eben Wissby",
    userName: "ewissby16",
    email: "ewissby16@youku.com",
    password: "jI2?aG>&d?0PIJH?",
    active: true,
  },
  {
    fullName: "Beauregard Frewer",
    userName: "bfrewer17",
    email: "bfrewer17@webeden.co.uk",
    password: "lD4|4!9f1wP",
    active: true,
  },
  {
    fullName: "De witt Splaven",
    userName: "dwitt18",
    email: "dwitt18@barnesandnoble.com",
    password: 'fJ6#`AW/y"jC!O/',
    active: false,
  },
  {
    fullName: "Kurt McGuirk",
    userName: "kmcguirk19",
    email: "kmcguirk19@wordpress.com",
    password: "wE2/ULBs@A",
    active: true,
  },
  {
    fullName: "Melly Shuttlewood",
    userName: "mshuttlewood1a",
    email: "mshuttlewood1a@amazon.co.uk",
    password: "gA4?RK6N",
    active: true,
  },
  {
    fullName: "Rosalinda Ties",
    userName: "rties1b",
    email: "rties1b@reddit.com",
    password: "kL0|XzH+S",
    active: false,
  },
  {
    fullName: "Shawn Latour",
    userName: "slatour1c",
    email: "slatour1c@yellowbook.com",
    password: "zM5,cVd3?gP",
    active: false,
  },
  {
    fullName: "Rafaello O'Daly",
    userName: "rodaly1d",
    email: "rodaly1d@nydailynews.com",
    password: "fA4$_/,0=,,zDugb",
    active: true,
  },
];
